name: Build Image for all Dockerfile

on:
  push:
    branches:
      - master

jobs:
  php_nodejs:
    uses: ./.github/workflows/reusable-push-image.yaml
    strategy:
      matrix:
        version:
          - 8.2
    with:
      project_name: php_nodejs
      file: Dockerfile
      tags: type=raw,value=${{ matrix.version }}
      build_args: |
        PHP_VERSION=${{ matrix.version }}
    secrets: inherit
  
  ssh-honeypot:
    uses: ./.github/workflows/reusable-push-image.yaml
    with:
      project_name: ssh-honeypot
      file: Dockerfile
    secrets: inherit
